add_first_endpoint
NikitaRudakow/ToDO_FastApi pull request #1
Opened 2023-04-12 12:51 UTC by NikitaRudakow

2023-04-12 13:10 UTC, MaksimLion requested changes

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +        }
нужно использовать схемы

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +    tasks = result.fetchall()
какой смысл от ОРМ если используешь execute и работаешь с кортежами
ищи способ вытягивать объекты

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +        subtasks = subresult.fetchall()
все запросы должны быть в слое репозитория

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +async def get_all_tasks(session: AsyncSession = Depends(get_async_session)):
роут не по стандартам рест

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +            subtask_dict = {
таски и сабтаски должны вытягиваться одним sql запросом

2023-04-12 13:10 UTC, MaksimLion commented on router.py
> +            task_dict["subtasks"].append(subtask_dict)
так делать нельзя

2023-04-12 13:11 UTC, MaksimLion commented
компоуз файл неверный

2023-04-12 13:11 UTC, MaksimLion commented
.idea должна быть в гит игноре

2023-04-12 13:12 UTC, MaksimLion commented
.DS_Store должно быть в гит игноре

2023-04-12 13:13 UTC, MaksimLion requested changes

2023-04-12 13:13 UTC, MaksimLion commented on router.py
> +)
роутеры должны быть в папке view

2023-04-12 13:15 UTC, MaksimLion requested changes

2023-04-12 13:15 UTC, MaksimLion commented on router.py
> +
лишние отступы

2023-04-12 13:15 UTC, MaksimLion commented on router.py
> +    for t in tasks:
не понятный нейминг `t`

2023-04-12 13:15 UTC, MaksimLion commented on router.py
> +@router.get("/get_all_tasks")
у роутера должна быть описана response_model

2023-04-12 13:15 UTC, MaksimLion commented on router.py
> +
от импортов 2 отступа

2023-04-12 13:17 UTC, MaksimLion requested changes

2023-04-12 13:17 UTC, MaksimLion commented on router.py
> +from fastapi_pagination.ext.sqlalchemy import paginate
целая куча неиспользуемых импортов

2023-04-12 13:19 UTC, MaksimLion commented
<img width="705" alt="image" src="https://user-images.githubusercontent.com/43618762/231469982-638ee12b-f479-455f-a8fc-1f60b3708e8d.png">
должна быть своя ветка
и пул реквест на дев

2023-04-12 13:21 UTC, MaksimLion commented on database.py
> +Base = declarative_base()
зачем тебе Base если ты его не используешь?

2023-04-18 19:09 UTC, artem-shlapakov requested changes

2023-04-18 19:09 UTC, artem-shlapakov commented on tests/test_tasks.py
> +    assert response.status_code == 200
апи отработала, а вдруг данные не обновились?) проверь, пожалуйста

2023-04-18 20:49 UTC, MaksimLion requested changes

2023-04-18 20:49 UTC, MaksimLion commented on app/migrations/versions/8bcd661ac159_db_delete_one_ficha.py
> +    # ### end Alembic commands ###
Целая куча пустых миграций

2023-04-18 20:49 UTC, MaksimLion commented on app/repositories/tasks.py
> +async def get_one_task(task_id: int):
get_task_by_id

2023-04-18 20:49 UTC, MaksimLion commented on app/views/tasks.py
> +    result = await repo_get_all_tasks(page, page_size)
Некорректно назван метод

2023-04-18 20:49 UTC, MaksimLion commented on docker-compose.test.yml
> +      - "5501:5432"
Расскажи почему именно эти порты взял?

2023-04-18 20:49 UTC, MaksimLion commented on tests/test_tasks.py
> +    response = await ac.get("http://127.0.0.1:8000/tasks", params={
Ты точно запускал тесты?

2023-04-19 11:19 UTC, NikitaRudakow commented on app/views/tasks.py
> +    result = await repo_get_all_tasks(page, page_size)
исправил на get_tasks

2023-04-19 11:20 UTC, NikitaRudakow commented on app/database.py
> +DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
вынес и убрал убрал POSTGRES_HOST, POSTGRES_DB, POSTGRES_PASSWORD, POSTGRES_PORT, POSTGRES_USER из импортов

2023-04-19 11:20 UTC, NikitaRudakow commented on app/repositories/tasks.py
> +        query = (delete(Task).where(Task.id == task_id))
исправил

2023-04-19 11:21 UTC, NikitaRudakow commented on app/views/tasks.py
> +async def get_all_tasks(page: int, page_size: int):
добавил, невнимательно прочитал задание

2023-04-19 11:21 UTC, NikitaRudakow commented on requirements.txt
> +psycopg2
исправил

2023-04-19 11:21 UTC, NikitaRudakow commented on tests/conftest.py
> +    async with AsyncClient(app=app, base_url="http://test") as ac:
исправил

2023-04-19 11:21 UTC, NikitaRudakow commented on tests/test_tasks.py
> +    response = await ac.post("http://127.0.0.1:8000/tasks", json={
исправил

2023-04-19 11:21 UTC, NikitaRudakow commented on tests/test_tasks.py
> +    response = await ac.get("http://127.0.0.1:8000/tasks", params={
исправил

2023-04-19 11:21 UTC, NikitaRudakow commented on tests/test_tasks.py
> +    response = await ac.get("http://127.0.0.1:8000/tasks/1", params={
исправил

2023-04-19 11:22 UTC, NikitaRudakow commented on tests/test_tasks.py
> +    response = await ac.delete("http://127.0.0.1:8000/tasks/1", params={
исправил

2023-04-19 11:22 UTC, NikitaRudakow commented on tests/test_tasks.py
> +        "http://127.0.0.1:8000/tasks/4", params={"task_id": 4},
исправил

2023-04-19 11:22 UTC, NikitaRudakow commented on app/migrations/versions/8bcd661ac159_db_delete_one_ficha.py
> +    # ### end Alembic commands ###
удалил пустые миграции

2023-04-19 11:22 UTC, NikitaRudakow commented on app/repositories/tasks.py
> +async def get_one_task(task_id: int):
переименовал

2023-04-19 11:23 UTC, NikitaRudakow commented on tests/test_tasks.py
> +    response = await ac.get("http://127.0.0.1:8000/tasks", params={
убрал http://127.0.0.1:8000 из всех тестов, сделал правильный base_url

2023-04-19 11:48 UTC, NikitaRudakow commented on README.md
> +run migrations:
сделал readme подробнее

2023-04-20 09:55 UTC, MaksimLion requested changes

2023-04-20 09:55 UTC, MaksimLion commented on tests/test_tasks.py
> +    assert response.status_code == 200
на delete 204 должно быть

2023-04-20 13:50 UTC, NikitaRudakow commented on app/repositories/tasks.py
> +    return await get_one_task(task_id)
Исправил

2023-04-29 07:51 UTC, merged